### ISSUE TITLE
Hi-Notch Issue: Finder Background Flickering

### ISSUE THREAD

**Issue by AlejandroVolkova** [MStankiewiczOfficial/Hi-Notch#2]
### Describe the bug

The Hi-Notch extension for BTT has an issue with the background that flickers whenever a Finder window is minimized or you click on the desktop or a Finder window.

When you minimize a Finder window or click on the desktop wallpaper or a Finder window, the Hi-Notch background flickers and appears to be an error. 

It would be helpful to investigate this issue and provide an update to fix this problem and improve the stability of the background in Hi-Notch.

### To Reproduce

To reproduce this issue, follow these steps:

1. Open the Finder application on your device.
2. Minimize a Finder window or click on the desktop or a Finder window.
3. Observe that the Hi-Notch background flickers.

### Expected behavior

Stable Background

### Screenshots

Here is a demonstration of the issue: [Video](https://github.com/MStankiewiczOfficial/Hi-Notch/assets/120342552/8cd1a9d1-af2c-4bd5-9ed5-d59815e4ebd2)

### Model of Mac

MacBookPro M1 Max

### macOS version

14.5

### Hi Notch! version

24031

### BetterTouchTool version

4.564

### Statements

- [X] I use the latest version of Hi Notch!
- [X] I use the latest stable version of BetterTouchTool
- [X] I verified that the error has not already been reported on GitHub.
- [X] I verified that the error has not already been reported on BTT Forum.

**Comment by stankiewiczmichal** [comment]
Thank you for your report. Unfortunately, the error is due to a delay generated by the BetterTouchTool software, which means that I am unable to patch it. I will contact the developer of the BTT software to consult on possible solutions.
