### ISSUE TITLE
will it support for monitor without Notch?

### ISSUE THREAD

**Issue by Jianfengliu0413** [MStankiewiczOfficial/Hi-Notch#3]
### Is your feature request related to a problem? Please describe

I used mac with the lid closed, and mainly use the external monitor. 

### Describe the solution you'd like

i know nothing

### Statements

- [X] I verified that the suggestion has not already been requested on GitHub.
- [X] I verified that the suggestion has not already been requested on BTT Forum.

**Comment by stankiewiczmichal** [comment]
This feature is not planned in the main version of Hi-Notch.
